In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(Path("household_power_consumption.txt"), sep=";", na_values="?")

df['datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], dayfirst=True)
df = df.dropna(subset=['Global_active_power'])

# Convert to hourly data
df = df.set_index('datetime')
df_hourly = df['Global_active_power'].resample('h').mean().dropna()
df_hourly = df_hourly.reset_index()
df_hourly.columns = ['datetime', 'power']

df_hourly['hour']      = df_hourly['datetime'].dt.hour
df_hourly['dayofweek'] = df_hourly['datetime'].dt.dayofweek
df_hourly['dayofyear'] = df_hourly['datetime'].dt.dayofyear

In [5]:
print(df.shape)
df.head()

(2049280, 9)

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
datetime,,,,,,,,,
2006-12-16 17:24:00,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
2006-12-16 17:25:00,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2006-12-16 17:26:00,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
2006-12-16 17:27:00,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
2006-12-16 17:28:00,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [3]:
print(df_hourly.shape)
df_hourly.head()

(34168, 5)

             datetime     power  hour  dayofweek  dayofyear
0 2006-12-16 17:00:00  4.222889    17          5        350
1 2006-12-16 18:00:00  3.632200    18          5        350
2 2006-12-16 19:00:00  3.400233    19          5        350
3 2006-12-16 20:00:00  3.268567    20          5        350
4 2006-12-16 21:00:00  3.056467    21          5        350